language:
- objective-c
env:
  matrix:
  - NODE_VERSION="4.1.1"
  global:
  - secure: BuCxvkJOa8k0NzsoiFDlJQjzj5+xcbnaA4+A8maNJDAe3etcBSZBA+4nxm18jABeuE9NNg5k2rayrGKhF6kqpy0TcgvtUOx38of0FP7zaO34kKwbPuKymvoLVJ58caQsQCbBGc/UTdBxHLTe8WN2G0wkRFmWg5YKNqg5rgyrNB5e8V1bWfILg/PRX5jla/59sG5+A/2vGa6HRpiEdRk0QvxUIJoHrh0DmkaOkQ3FK5wKd1vvfPfqQVLF6xiDjZ+C2203eqjcpapNz/6yX/C7X4XtSgNHcyOnWpcY2A9m+CYINzPfoAPnZJpdc5vWfDyR6rQJ/3PcG3Ol8M2eDwH2FjhaPpNwotrAHZUNod7WCaRaWVfb8Qku4fnO0LpQQ+eBIKbHCR4VeNWUo7EX7T3445oxxft7nwszaLpL1DYKFgoMAAbTclycJFUK4cZwYCSxOYKfdYKi9R5889TEw32FRCLrOjW3Pglqo2ljPsGk/pG8MmRzA2sI96xUFUwHuuUhmmbXd8oSCbWZjWaB3gxxVRKG26LfK8DAR6w0+7C42Z2JuNsdnQopTRxicbXCr13i5ZPOSrZrgEpwm3tHU3MCO5uXBlrpl4jwyBBqkQusJOiP1tc/5Iu008Y0cHty/Z5Juu1apaAm8NrXKkJt+jerewbIT4cSqYFzWRAfC8opQUc=
  - secure: LbuFSJhaqH8X84n9D754UN0dqeTbHEFU1Z4TRvtSZfG9tRrMWqvf5vOaiV/6fAqgLVo1eL5CUcEvrDrLxVLJTXs8V4UPJT+H8mUPVFlX4fOLCYDHllphUUnyDH7rPSb5QkfPAIa0rl5YtHPpMi0HwYD75L5uEwZGJEaj1rE/BqjrXROoCakIRcgi2GzUA3WiPSQPxry2AEI948Kv+jotD990UjRYQDlx+RCdS3bzHaBHvKJPKvVNWaf+g29xNZI3vMu7bZZj25BeheOmta1mMfGduSEKjxc4BukHOaN7ydyjiVEMIvqx5es3VQNr0CfJpkZAS3Y+6r2GxZ4zmUdwEKH5nJZ5RmKvXt4L3mp+fs1W5IdOCmxihJtRvt+JjZGEDdgqx33t2uv+kZOdaFHpVzD8DdQZfcfzTgLS3TFSo/7QgbAlCq88kwV+OwHoIPiW07cqHHon4pyS5IdvX8L0wEymLXna+l2TM0eELGnttd4mFu1BBgWg2HLoQKohmCztcof1bw+63Ugi2nFdsHWPfOqvQGhyXBBHMcFdWO7a1fm3JaQvD99svl6vNyI58q7byHTYVoHcMTVGSTYA4bEe2s6l/GIJTiJP5y8d9uLz9ASq6OKUJ/8OCulFbzLzN/BkJ09r7kmVGJsNkyUyuqFtLBMsR0fzUPNahLsj8+v0Ns8=
before_install:
- openssl aes-256-cbc -K $encrypted_2eef65e88e3a_key -iv $encrypted_2eef65e88e3a_iv
  -in livestyle.tar.enc -out livestyle.tar -d
- tar xvf livestyle.tar
- ./tools/osx/import-key.sh
install:
- rm -rf ~/.nvm
- git clone https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- node --version
- npm install
- npm test
- npm run publish
after_script:
- rm livestyle.tar livestyle.cer livestyle.p12
- security delete-keychain osx-build.keychain
branches:
  only:
  - master
